# Generated by Django 5.1.6 on 2025-03-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
