# Generated by Django 5.1.6 on 2025-03-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_order'),
        ('sales', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
