# Generated by Django 5.1.6 on 2025-03-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_product_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery',
            field=models.CharField(choices=[('Xmill', 'X.Mill'), ('Pohonch', 'Pohonch')], default='X.Mill', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='unit',
            field=models.CharField(choices=[('CTN', 'Ctn'), ('Pouch', 'Pouch')], default='Ctn', max_length=20),
        ),
    ]
