# Generated by Django 5.1.6 on 2025-03-12 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesorder_delivery_salesorder_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
