# Generated by Django 5.1.6 on 2025-03-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesorder_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
