# Generated by Django 5.1.7 on 2025-03-27 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=20)),
                ('invoice_qty', models.IntegerField(default=1)),
                ('invoice_rate', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('invoice_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder')),
            ],
        ),
    ]
