# Generated by Django 5.1.7 on 2025-03-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='remaining_qty',
            field=models.IntegerField(default=0),
        ),
    ]
