# Generated by Django 5.1.7 on 2025-03-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesorder_invoice_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='invoice_qty',
            new_name='invoiced_qty',
        ),
    ]
