# Generated by Django 5.1.7 on 2025-03-30 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_price_remove_product_stock_quantity'),
        ('sales', '0012_alter_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_unit',
            field=models.CharField(choices=[('CTN', 'Ctn'), ('Pouch', 'Pouch')], default='Ctn', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
